from fpdf import FPDF
import os
from datetime import datetime

class InsightIQReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_fill_color(31, 119, 180)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, "InsightIQ - Executive Business Report", align="C", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Generated by InsightIQ | {datetime.now().strftime('%Y-%m-%d %H:%M')} | Page {self.page_no()}", align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 13)
        self.set_fill_color(240, 248, 255)
        self.set_text_color(31, 119, 180)
        self.cell(0, 10, title, fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def body_text(self, text):
        self.set_font("Helvetica", "", 10)
        # Strip all non-ASCII characters
        clean = text.encode("ascii", "ignore").decode("ascii").strip()
        if clean:
            self.multi_cell(0, 7, clean)
            self.ln(2)

    def kpi_row(self, label, value):
        self.set_font("Helvetica", "B", 10)
        clean_label = label.encode("ascii", "ignore").decode("ascii").strip()
        clean_value = str(value).encode("ascii", "ignore").decode("ascii").strip()
        self.cell(80, 8, clean_label, border=1)
        self.set_font("Helvetica", "", 10)
        self.cell(100, 8, clean_value, border=1, new_x="LMARGIN", new_y="NEXT")


def generate_pdf_report(kpis: dict, insights: list, recommendations: list) -> str:
    pdf = InsightIQReport()
    pdf.add_page()

    # Cover Info
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Report Date: {datetime.now().strftime('%B %d, %Y')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, "Dataset: Superstore Sales | Powered by Groq + LLaMA 3", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # KPI Summary
    pdf.section_title("1. Key Performance Indicators")
    pdf.kpi_row("Total Revenue", f"${kpis.get('total_revenue', 0):,.2f}")
    pdf.kpi_row("Total Orders", f"{kpis.get('total_orders', 0):,}")
    pdf.kpi_row("Total Customers", f"{kpis.get('total_customers', 0):,}")
    pdf.kpi_row("Total Products", f"{kpis.get('total_products', 0):,}")
    pdf.kpi_row("Avg Order Value", f"${kpis.get('avg_order_value', 0):,.2f}")
    pdf.kpi_row("Revenue Per Customer", f"${kpis.get('revenue_per_customer', 0):,.2f}")
    pdf.kpi_row("Top Region", str(kpis.get('top_region', 'N/A')))
    pdf.kpi_row("Top Category", str(kpis.get('top_category', 'N/A')))
    pdf.kpi_row("Top Segment", str(kpis.get('top_segment', 'N/A')))
    pdf.ln(6)

    # Regional Breakdown
    pdf.section_title("2. Regional Sales Breakdown")
    regional = kpis.get("regional_sales", {})
    total = sum(regional.values()) if regional else 1
    for region, sales in regional.items():
        pct = round((sales / total) * 100, 1)
        pdf.kpi_row(region, f"${sales:,.2f} ({pct}%)")
    pdf.ln(6)

    # Yearly Trend
    pdf.section_title("3. Year-over-Year Revenue Trend")
    yearly = kpis.get("yearly_sales", {})
    years = sorted(yearly.keys())
    for i, year in enumerate(years):
        if i == 0:
            pdf.kpi_row(str(year), f"${yearly[year]:,.2f} (baseline)")
        else:
            prev = yearly[years[i-1]]
            growth = round(((yearly[year] - prev) / prev) * 100, 1)
            arrow = "+" if growth > 0 else "-"
            pdf.kpi_row(str(year), f"${yearly[year]:,.2f} ({arrow}{abs(growth)}% YoY)")
    pdf.ln(6)

    # Business Insights
    pdf.section_title("4. Auto-Generated Business Insights")
    highlight_insights = [i for i in insights if i["type"] in ["highlight", "growth", "kpi"]]
    for insight in highlight_insights[:8]:
        pdf.body_text(f"- {insight['title']}: {insight['value']}")
    pdf.ln(4)

    # Recommendations
    pdf.section_title("5. Strategic Recommendations")
    for rec in recommendations:
        pdf.body_text(f"- {rec}")
    pdf.ln(4)

    # Top Products
    pdf.section_title("6. Top 10 Products by Revenue")
    top_products = kpis.get("top_10_products", [])
    for rank, (product, sales) in enumerate(top_products, 1):
        short_name = product[:45] + "..." if len(product) > 45 else product
        pdf.kpi_row(f"{rank}. {short_name}", f"${sales:,.2f}")
    pdf.ln(6)

    # Save
    os.makedirs("exports", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filepath = f"exports/InsightIQ_Report_{timestamp}.pdf"
    pdf.output(filepath)
    print(f"PDF saved: {filepath}")
    return filepath